// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: config.proto
// Protobuf C++ Version: 5.27.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_config_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_config_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_config_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_config_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_config_2eproto;
class cameraConfiguration;
struct cameraConfigurationDefaultTypeInternal;
extern cameraConfigurationDefaultTypeInternal _cameraConfiguration_default_instance_;
class systemConfiguration;
struct systemConfigurationDefaultTypeInternal;
extern systemConfigurationDefaultTypeInternal _systemConfiguration_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class cameraConfiguration final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cameraConfiguration) */ {
 public:
  inline cameraConfiguration() : cameraConfiguration(nullptr) {}
  ~cameraConfiguration() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR cameraConfiguration(
      ::google::protobuf::internal::ConstantInitialized);

  inline cameraConfiguration(const cameraConfiguration& from) : cameraConfiguration(nullptr, from) {}
  inline cameraConfiguration(cameraConfiguration&& from) noexcept
      : cameraConfiguration(nullptr, std::move(from)) {}
  inline cameraConfiguration& operator=(const cameraConfiguration& from) {
    CopyFrom(from);
    return *this;
  }
  inline cameraConfiguration& operator=(cameraConfiguration&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const cameraConfiguration& default_instance() {
    return *internal_default_instance();
  }
  static inline const cameraConfiguration* internal_default_instance() {
    return reinterpret_cast<const cameraConfiguration*>(
        &_cameraConfiguration_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(cameraConfiguration& a, cameraConfiguration& b) { a.Swap(&b); }
  inline void Swap(cameraConfiguration* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(cameraConfiguration* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  cameraConfiguration* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<cameraConfiguration>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const cameraConfiguration& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const cameraConfiguration& from) { cameraConfiguration::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(cameraConfiguration* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "cameraConfiguration"; }

 protected:
  explicit cameraConfiguration(::google::protobuf::Arena* arena);
  cameraConfiguration(::google::protobuf::Arena* arena, const cameraConfiguration& from);
  cameraConfiguration(::google::protobuf::Arena* arena, cameraConfiguration&& from) noexcept
      : cameraConfiguration(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDeviceIDFieldNumber = 1,
    kFocalLengthFieldNumber = 2,
    kPixelSizeFieldNumber = 3,
    kFovFieldNumber = 4,
    kXResolutionFieldNumber = 5,
    kYResolutionFieldNumber = 6,
    kPixelRateFieldNumber = 7,
    kIndexFieldNumber = 8,
  };
  // string deviceID = 1;
  void clear_deviceid() ;
  const std::string& deviceid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_deviceid(Arg_&& arg, Args_... args);
  std::string* mutable_deviceid();
  PROTOBUF_NODISCARD std::string* release_deviceid();
  void set_allocated_deviceid(std::string* value);

  private:
  const std::string& _internal_deviceid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_deviceid(
      const std::string& value);
  std::string* _internal_mutable_deviceid();

  public:
  // double focalLength = 2;
  void clear_focallength() ;
  double focallength() const;
  void set_focallength(double value);

  private:
  double _internal_focallength() const;
  void _internal_set_focallength(double value);

  public:
  // double pixelSize = 3;
  void clear_pixelsize() ;
  double pixelsize() const;
  void set_pixelsize(double value);

  private:
  double _internal_pixelsize() const;
  void _internal_set_pixelsize(double value);

  public:
  // double fov = 4;
  void clear_fov() ;
  double fov() const;
  void set_fov(double value);

  private:
  double _internal_fov() const;
  void _internal_set_fov(double value);

  public:
  // int32 xResolution = 5;
  void clear_xresolution() ;
  ::int32_t xresolution() const;
  void set_xresolution(::int32_t value);

  private:
  ::int32_t _internal_xresolution() const;
  void _internal_set_xresolution(::int32_t value);

  public:
  // int32 yResolution = 6;
  void clear_yresolution() ;
  ::int32_t yresolution() const;
  void set_yresolution(::int32_t value);

  private:
  ::int32_t _internal_yresolution() const;
  void _internal_set_yresolution(::int32_t value);

  public:
  // double pixelRate = 7;
  void clear_pixelrate() ;
  double pixelrate() const;
  void set_pixelrate(double value);

  private:
  double _internal_pixelrate() const;
  void _internal_set_pixelrate(double value);

  public:
  // int32 index = 8;
  void clear_index() ;
  ::int32_t index() const;
  void set_index(::int32_t value);

  private:
  ::int32_t _internal_index() const;
  void _internal_set_index(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:cameraConfiguration)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 8, 0,
      44, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_cameraConfiguration_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const cameraConfiguration& from_msg);
    ::google::protobuf::internal::ArenaStringPtr deviceid_;
    double focallength_;
    double pixelsize_;
    double fov_;
    ::int32_t xresolution_;
    ::int32_t yresolution_;
    double pixelrate_;
    ::int32_t index_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_config_2eproto;
};
// -------------------------------------------------------------------

class systemConfiguration final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:systemConfiguration) */ {
 public:
  inline systemConfiguration() : systemConfiguration(nullptr) {}
  ~systemConfiguration() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR systemConfiguration(
      ::google::protobuf::internal::ConstantInitialized);

  inline systemConfiguration(const systemConfiguration& from) : systemConfiguration(nullptr, from) {}
  inline systemConfiguration(systemConfiguration&& from) noexcept
      : systemConfiguration(nullptr, std::move(from)) {}
  inline systemConfiguration& operator=(const systemConfiguration& from) {
    CopyFrom(from);
    return *this;
  }
  inline systemConfiguration& operator=(systemConfiguration&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const systemConfiguration& default_instance() {
    return *internal_default_instance();
  }
  static inline const systemConfiguration* internal_default_instance() {
    return reinterpret_cast<const systemConfiguration*>(
        &_systemConfiguration_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(systemConfiguration& a, systemConfiguration& b) { a.Swap(&b); }
  inline void Swap(systemConfiguration* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(systemConfiguration* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  systemConfiguration* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<systemConfiguration>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const systemConfiguration& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const systemConfiguration& from) { systemConfiguration::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(systemConfiguration* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "systemConfiguration"; }

 protected:
  explicit systemConfiguration(::google::protobuf::Arena* arena);
  systemConfiguration(::google::protobuf::Arena* arena, const systemConfiguration& from);
  systemConfiguration(::google::protobuf::Arena* arena, systemConfiguration&& from) noexcept
      : systemConfiguration(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCamerasFieldNumber = 1,
    kCentroidAlgoFieldNumber = 2,
    kAttitudeAlgoFieldNumber = 3,
    kDatabasePathFieldNumber = 5,
    kIdAlgoFieldNumber = 6,
    kCentroidMagFilterFieldNumber = 4,
    kAngularToleranceFieldNumber = 8,
    kCentroidFilterBrightestFieldNumber = 9,
    kEstimatedNumFalseStarsFieldNumber = 10,
    kMaxMismatchProbFieldNumber = 11,
    kCentroidCompareThresholdFieldNumber = 12,
    kAttitudeCompareThresholdFieldNumber = 13,
  };
  // repeated .cameraConfiguration cameras = 1;
  int cameras_size() const;
  private:
  int _internal_cameras_size() const;

  public:
  void clear_cameras() ;
  ::cameraConfiguration* mutable_cameras(int index);
  ::google::protobuf::RepeatedPtrField<::cameraConfiguration>* mutable_cameras();

  private:
  const ::google::protobuf::RepeatedPtrField<::cameraConfiguration>& _internal_cameras() const;
  ::google::protobuf::RepeatedPtrField<::cameraConfiguration>* _internal_mutable_cameras();
  public:
  const ::cameraConfiguration& cameras(int index) const;
  ::cameraConfiguration* add_cameras();
  const ::google::protobuf::RepeatedPtrField<::cameraConfiguration>& cameras() const;
  // string centroidAlgo = 2;
  void clear_centroidalgo() ;
  const std::string& centroidalgo() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_centroidalgo(Arg_&& arg, Args_... args);
  std::string* mutable_centroidalgo();
  PROTOBUF_NODISCARD std::string* release_centroidalgo();
  void set_allocated_centroidalgo(std::string* value);

  private:
  const std::string& _internal_centroidalgo() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_centroidalgo(
      const std::string& value);
  std::string* _internal_mutable_centroidalgo();

  public:
  // string attitudeAlgo = 3;
  void clear_attitudealgo() ;
  const std::string& attitudealgo() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_attitudealgo(Arg_&& arg, Args_... args);
  std::string* mutable_attitudealgo();
  PROTOBUF_NODISCARD std::string* release_attitudealgo();
  void set_allocated_attitudealgo(std::string* value);

  private:
  const std::string& _internal_attitudealgo() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_attitudealgo(
      const std::string& value);
  std::string* _internal_mutable_attitudealgo();

  public:
  // string databasePath = 5;
  void clear_databasepath() ;
  const std::string& databasepath() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_databasepath(Arg_&& arg, Args_... args);
  std::string* mutable_databasepath();
  PROTOBUF_NODISCARD std::string* release_databasepath();
  void set_allocated_databasepath(std::string* value);

  private:
  const std::string& _internal_databasepath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_databasepath(
      const std::string& value);
  std::string* _internal_mutable_databasepath();

  public:
  // string idAlgo = 6;
  void clear_idalgo() ;
  const std::string& idalgo() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_idalgo(Arg_&& arg, Args_... args);
  std::string* mutable_idalgo();
  PROTOBUF_NODISCARD std::string* release_idalgo();
  void set_allocated_idalgo(std::string* value);

  private:
  const std::string& _internal_idalgo() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_idalgo(
      const std::string& value);
  std::string* _internal_mutable_idalgo();

  public:
  // double centroidMagFilter = 4;
  void clear_centroidmagfilter() ;
  double centroidmagfilter() const;
  void set_centroidmagfilter(double value);

  private:
  double _internal_centroidmagfilter() const;
  void _internal_set_centroidmagfilter(double value);

  public:
  // double angularTolerance = 8;
  void clear_angulartolerance() ;
  double angulartolerance() const;
  void set_angulartolerance(double value);

  private:
  double _internal_angulartolerance() const;
  void _internal_set_angulartolerance(double value);

  public:
  // int32 centroidFilterBrightest = 9;
  void clear_centroidfilterbrightest() ;
  ::int32_t centroidfilterbrightest() const;
  void set_centroidfilterbrightest(::int32_t value);

  private:
  ::int32_t _internal_centroidfilterbrightest() const;
  void _internal_set_centroidfilterbrightest(::int32_t value);

  public:
  // int32 estimatedNumFalseStars = 10;
  void clear_estimatednumfalsestars() ;
  ::int32_t estimatednumfalsestars() const;
  void set_estimatednumfalsestars(::int32_t value);

  private:
  ::int32_t _internal_estimatednumfalsestars() const;
  void _internal_set_estimatednumfalsestars(::int32_t value);

  public:
  // float maxMismatchProb = 11;
  void clear_maxmismatchprob() ;
  float maxmismatchprob() const;
  void set_maxmismatchprob(float value);

  private:
  float _internal_maxmismatchprob() const;
  void _internal_set_maxmismatchprob(float value);

  public:
  // float centroidCompareThreshold = 12;
  void clear_centroidcomparethreshold() ;
  float centroidcomparethreshold() const;
  void set_centroidcomparethreshold(float value);

  private:
  float _internal_centroidcomparethreshold() const;
  void _internal_set_centroidcomparethreshold(float value);

  public:
  // float attitudeCompareThreshold = 13;
  void clear_attitudecomparethreshold() ;
  float attitudecomparethreshold() const;
  void set_attitudecomparethreshold(float value);

  private:
  float _internal_attitudecomparethreshold() const;
  void _internal_set_attitudecomparethreshold(float value);

  public:
  // @@protoc_insertion_point(class_scope:systemConfiguration)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 12, 1,
      78, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_systemConfiguration_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const systemConfiguration& from_msg);
    ::google::protobuf::RepeatedPtrField< ::cameraConfiguration > cameras_;
    ::google::protobuf::internal::ArenaStringPtr centroidalgo_;
    ::google::protobuf::internal::ArenaStringPtr attitudealgo_;
    ::google::protobuf::internal::ArenaStringPtr databasepath_;
    ::google::protobuf::internal::ArenaStringPtr idalgo_;
    double centroidmagfilter_;
    double angulartolerance_;
    ::int32_t centroidfilterbrightest_;
    ::int32_t estimatednumfalsestars_;
    float maxmismatchprob_;
    float centroidcomparethreshold_;
    float attitudecomparethreshold_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_config_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// cameraConfiguration

// int32 index = 8;
inline void cameraConfiguration::clear_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.index_ = 0;
}
inline ::int32_t cameraConfiguration::index() const {
  // @@protoc_insertion_point(field_get:cameraConfiguration.index)
  return _internal_index();
}
inline void cameraConfiguration::set_index(::int32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:cameraConfiguration.index)
}
inline ::int32_t cameraConfiguration::_internal_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.index_;
}
inline void cameraConfiguration::_internal_set_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.index_ = value;
}

// string deviceID = 1;
inline void cameraConfiguration::clear_deviceid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.deviceid_.ClearToEmpty();
}
inline const std::string& cameraConfiguration::deviceid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cameraConfiguration.deviceID)
  return _internal_deviceid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void cameraConfiguration::set_deviceid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.deviceid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cameraConfiguration.deviceID)
}
inline std::string* cameraConfiguration::mutable_deviceid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_deviceid();
  // @@protoc_insertion_point(field_mutable:cameraConfiguration.deviceID)
  return _s;
}
inline const std::string& cameraConfiguration::_internal_deviceid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.deviceid_.Get();
}
inline void cameraConfiguration::_internal_set_deviceid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.deviceid_.Set(value, GetArena());
}
inline std::string* cameraConfiguration::_internal_mutable_deviceid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.deviceid_.Mutable( GetArena());
}
inline std::string* cameraConfiguration::release_deviceid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cameraConfiguration.deviceID)
  return _impl_.deviceid_.Release();
}
inline void cameraConfiguration::set_allocated_deviceid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.deviceid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.deviceid_.IsDefault()) {
          _impl_.deviceid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cameraConfiguration.deviceID)
}

// double focalLength = 2;
inline void cameraConfiguration::clear_focallength() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.focallength_ = 0;
}
inline double cameraConfiguration::focallength() const {
  // @@protoc_insertion_point(field_get:cameraConfiguration.focalLength)
  return _internal_focallength();
}
inline void cameraConfiguration::set_focallength(double value) {
  _internal_set_focallength(value);
  // @@protoc_insertion_point(field_set:cameraConfiguration.focalLength)
}
inline double cameraConfiguration::_internal_focallength() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.focallength_;
}
inline void cameraConfiguration::_internal_set_focallength(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.focallength_ = value;
}

// double pixelSize = 3;
inline void cameraConfiguration::clear_pixelsize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pixelsize_ = 0;
}
inline double cameraConfiguration::pixelsize() const {
  // @@protoc_insertion_point(field_get:cameraConfiguration.pixelSize)
  return _internal_pixelsize();
}
inline void cameraConfiguration::set_pixelsize(double value) {
  _internal_set_pixelsize(value);
  // @@protoc_insertion_point(field_set:cameraConfiguration.pixelSize)
}
inline double cameraConfiguration::_internal_pixelsize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pixelsize_;
}
inline void cameraConfiguration::_internal_set_pixelsize(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pixelsize_ = value;
}

// double fov = 4;
inline void cameraConfiguration::clear_fov() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fov_ = 0;
}
inline double cameraConfiguration::fov() const {
  // @@protoc_insertion_point(field_get:cameraConfiguration.fov)
  return _internal_fov();
}
inline void cameraConfiguration::set_fov(double value) {
  _internal_set_fov(value);
  // @@protoc_insertion_point(field_set:cameraConfiguration.fov)
}
inline double cameraConfiguration::_internal_fov() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fov_;
}
inline void cameraConfiguration::_internal_set_fov(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fov_ = value;
}

// int32 xResolution = 5;
inline void cameraConfiguration::clear_xresolution() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xresolution_ = 0;
}
inline ::int32_t cameraConfiguration::xresolution() const {
  // @@protoc_insertion_point(field_get:cameraConfiguration.xResolution)
  return _internal_xresolution();
}
inline void cameraConfiguration::set_xresolution(::int32_t value) {
  _internal_set_xresolution(value);
  // @@protoc_insertion_point(field_set:cameraConfiguration.xResolution)
}
inline ::int32_t cameraConfiguration::_internal_xresolution() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.xresolution_;
}
inline void cameraConfiguration::_internal_set_xresolution(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xresolution_ = value;
}

// int32 yResolution = 6;
inline void cameraConfiguration::clear_yresolution() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yresolution_ = 0;
}
inline ::int32_t cameraConfiguration::yresolution() const {
  // @@protoc_insertion_point(field_get:cameraConfiguration.yResolution)
  return _internal_yresolution();
}
inline void cameraConfiguration::set_yresolution(::int32_t value) {
  _internal_set_yresolution(value);
  // @@protoc_insertion_point(field_set:cameraConfiguration.yResolution)
}
inline ::int32_t cameraConfiguration::_internal_yresolution() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.yresolution_;
}
inline void cameraConfiguration::_internal_set_yresolution(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yresolution_ = value;
}

// double pixelRate = 7;
inline void cameraConfiguration::clear_pixelrate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pixelrate_ = 0;
}
inline double cameraConfiguration::pixelrate() const {
  // @@protoc_insertion_point(field_get:cameraConfiguration.pixelRate)
  return _internal_pixelrate();
}
inline void cameraConfiguration::set_pixelrate(double value) {
  _internal_set_pixelrate(value);
  // @@protoc_insertion_point(field_set:cameraConfiguration.pixelRate)
}
inline double cameraConfiguration::_internal_pixelrate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pixelrate_;
}
inline void cameraConfiguration::_internal_set_pixelrate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pixelrate_ = value;
}

// -------------------------------------------------------------------

// systemConfiguration

// repeated .cameraConfiguration cameras = 1;
inline int systemConfiguration::_internal_cameras_size() const {
  return _internal_cameras().size();
}
inline int systemConfiguration::cameras_size() const {
  return _internal_cameras_size();
}
inline void systemConfiguration::clear_cameras() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cameras_.Clear();
}
inline ::cameraConfiguration* systemConfiguration::mutable_cameras(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:systemConfiguration.cameras)
  return _internal_mutable_cameras()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::cameraConfiguration>* systemConfiguration::mutable_cameras()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:systemConfiguration.cameras)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_cameras();
}
inline const ::cameraConfiguration& systemConfiguration::cameras(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:systemConfiguration.cameras)
  return _internal_cameras().Get(index);
}
inline ::cameraConfiguration* systemConfiguration::add_cameras() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::cameraConfiguration* _add = _internal_mutable_cameras()->Add();
  // @@protoc_insertion_point(field_add:systemConfiguration.cameras)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::cameraConfiguration>& systemConfiguration::cameras() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:systemConfiguration.cameras)
  return _internal_cameras();
}
inline const ::google::protobuf::RepeatedPtrField<::cameraConfiguration>&
systemConfiguration::_internal_cameras() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cameras_;
}
inline ::google::protobuf::RepeatedPtrField<::cameraConfiguration>*
systemConfiguration::_internal_mutable_cameras() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.cameras_;
}

// string centroidAlgo = 2;
inline void systemConfiguration::clear_centroidalgo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.centroidalgo_.ClearToEmpty();
}
inline const std::string& systemConfiguration::centroidalgo() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:systemConfiguration.centroidAlgo)
  return _internal_centroidalgo();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void systemConfiguration::set_centroidalgo(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.centroidalgo_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:systemConfiguration.centroidAlgo)
}
inline std::string* systemConfiguration::mutable_centroidalgo() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_centroidalgo();
  // @@protoc_insertion_point(field_mutable:systemConfiguration.centroidAlgo)
  return _s;
}
inline const std::string& systemConfiguration::_internal_centroidalgo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.centroidalgo_.Get();
}
inline void systemConfiguration::_internal_set_centroidalgo(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.centroidalgo_.Set(value, GetArena());
}
inline std::string* systemConfiguration::_internal_mutable_centroidalgo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.centroidalgo_.Mutable( GetArena());
}
inline std::string* systemConfiguration::release_centroidalgo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:systemConfiguration.centroidAlgo)
  return _impl_.centroidalgo_.Release();
}
inline void systemConfiguration::set_allocated_centroidalgo(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.centroidalgo_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.centroidalgo_.IsDefault()) {
          _impl_.centroidalgo_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:systemConfiguration.centroidAlgo)
}

// string attitudeAlgo = 3;
inline void systemConfiguration::clear_attitudealgo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attitudealgo_.ClearToEmpty();
}
inline const std::string& systemConfiguration::attitudealgo() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:systemConfiguration.attitudeAlgo)
  return _internal_attitudealgo();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void systemConfiguration::set_attitudealgo(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attitudealgo_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:systemConfiguration.attitudeAlgo)
}
inline std::string* systemConfiguration::mutable_attitudealgo() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_attitudealgo();
  // @@protoc_insertion_point(field_mutable:systemConfiguration.attitudeAlgo)
  return _s;
}
inline const std::string& systemConfiguration::_internal_attitudealgo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.attitudealgo_.Get();
}
inline void systemConfiguration::_internal_set_attitudealgo(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attitudealgo_.Set(value, GetArena());
}
inline std::string* systemConfiguration::_internal_mutable_attitudealgo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.attitudealgo_.Mutable( GetArena());
}
inline std::string* systemConfiguration::release_attitudealgo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:systemConfiguration.attitudeAlgo)
  return _impl_.attitudealgo_.Release();
}
inline void systemConfiguration::set_allocated_attitudealgo(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attitudealgo_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.attitudealgo_.IsDefault()) {
          _impl_.attitudealgo_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:systemConfiguration.attitudeAlgo)
}

// double centroidMagFilter = 4;
inline void systemConfiguration::clear_centroidmagfilter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.centroidmagfilter_ = 0;
}
inline double systemConfiguration::centroidmagfilter() const {
  // @@protoc_insertion_point(field_get:systemConfiguration.centroidMagFilter)
  return _internal_centroidmagfilter();
}
inline void systemConfiguration::set_centroidmagfilter(double value) {
  _internal_set_centroidmagfilter(value);
  // @@protoc_insertion_point(field_set:systemConfiguration.centroidMagFilter)
}
inline double systemConfiguration::_internal_centroidmagfilter() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.centroidmagfilter_;
}
inline void systemConfiguration::_internal_set_centroidmagfilter(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.centroidmagfilter_ = value;
}

// string databasePath = 5;
inline void systemConfiguration::clear_databasepath() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.databasepath_.ClearToEmpty();
}
inline const std::string& systemConfiguration::databasepath() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:systemConfiguration.databasePath)
  return _internal_databasepath();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void systemConfiguration::set_databasepath(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.databasepath_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:systemConfiguration.databasePath)
}
inline std::string* systemConfiguration::mutable_databasepath() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_databasepath();
  // @@protoc_insertion_point(field_mutable:systemConfiguration.databasePath)
  return _s;
}
inline const std::string& systemConfiguration::_internal_databasepath() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.databasepath_.Get();
}
inline void systemConfiguration::_internal_set_databasepath(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.databasepath_.Set(value, GetArena());
}
inline std::string* systemConfiguration::_internal_mutable_databasepath() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.databasepath_.Mutable( GetArena());
}
inline std::string* systemConfiguration::release_databasepath() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:systemConfiguration.databasePath)
  return _impl_.databasepath_.Release();
}
inline void systemConfiguration::set_allocated_databasepath(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.databasepath_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.databasepath_.IsDefault()) {
          _impl_.databasepath_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:systemConfiguration.databasePath)
}

// string idAlgo = 6;
inline void systemConfiguration::clear_idalgo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idalgo_.ClearToEmpty();
}
inline const std::string& systemConfiguration::idalgo() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:systemConfiguration.idAlgo)
  return _internal_idalgo();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void systemConfiguration::set_idalgo(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idalgo_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:systemConfiguration.idAlgo)
}
inline std::string* systemConfiguration::mutable_idalgo() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_idalgo();
  // @@protoc_insertion_point(field_mutable:systemConfiguration.idAlgo)
  return _s;
}
inline const std::string& systemConfiguration::_internal_idalgo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idalgo_.Get();
}
inline void systemConfiguration::_internal_set_idalgo(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idalgo_.Set(value, GetArena());
}
inline std::string* systemConfiguration::_internal_mutable_idalgo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.idalgo_.Mutable( GetArena());
}
inline std::string* systemConfiguration::release_idalgo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:systemConfiguration.idAlgo)
  return _impl_.idalgo_.Release();
}
inline void systemConfiguration::set_allocated_idalgo(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idalgo_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.idalgo_.IsDefault()) {
          _impl_.idalgo_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:systemConfiguration.idAlgo)
}

// double angularTolerance = 8;
inline void systemConfiguration::clear_angulartolerance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angulartolerance_ = 0;
}
inline double systemConfiguration::angulartolerance() const {
  // @@protoc_insertion_point(field_get:systemConfiguration.angularTolerance)
  return _internal_angulartolerance();
}
inline void systemConfiguration::set_angulartolerance(double value) {
  _internal_set_angulartolerance(value);
  // @@protoc_insertion_point(field_set:systemConfiguration.angularTolerance)
}
inline double systemConfiguration::_internal_angulartolerance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.angulartolerance_;
}
inline void systemConfiguration::_internal_set_angulartolerance(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angulartolerance_ = value;
}

// int32 centroidFilterBrightest = 9;
inline void systemConfiguration::clear_centroidfilterbrightest() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.centroidfilterbrightest_ = 0;
}
inline ::int32_t systemConfiguration::centroidfilterbrightest() const {
  // @@protoc_insertion_point(field_get:systemConfiguration.centroidFilterBrightest)
  return _internal_centroidfilterbrightest();
}
inline void systemConfiguration::set_centroidfilterbrightest(::int32_t value) {
  _internal_set_centroidfilterbrightest(value);
  // @@protoc_insertion_point(field_set:systemConfiguration.centroidFilterBrightest)
}
inline ::int32_t systemConfiguration::_internal_centroidfilterbrightest() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.centroidfilterbrightest_;
}
inline void systemConfiguration::_internal_set_centroidfilterbrightest(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.centroidfilterbrightest_ = value;
}

// int32 estimatedNumFalseStars = 10;
inline void systemConfiguration::clear_estimatednumfalsestars() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.estimatednumfalsestars_ = 0;
}
inline ::int32_t systemConfiguration::estimatednumfalsestars() const {
  // @@protoc_insertion_point(field_get:systemConfiguration.estimatedNumFalseStars)
  return _internal_estimatednumfalsestars();
}
inline void systemConfiguration::set_estimatednumfalsestars(::int32_t value) {
  _internal_set_estimatednumfalsestars(value);
  // @@protoc_insertion_point(field_set:systemConfiguration.estimatedNumFalseStars)
}
inline ::int32_t systemConfiguration::_internal_estimatednumfalsestars() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.estimatednumfalsestars_;
}
inline void systemConfiguration::_internal_set_estimatednumfalsestars(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.estimatednumfalsestars_ = value;
}

// float maxMismatchProb = 11;
inline void systemConfiguration::clear_maxmismatchprob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.maxmismatchprob_ = 0;
}
inline float systemConfiguration::maxmismatchprob() const {
  // @@protoc_insertion_point(field_get:systemConfiguration.maxMismatchProb)
  return _internal_maxmismatchprob();
}
inline void systemConfiguration::set_maxmismatchprob(float value) {
  _internal_set_maxmismatchprob(value);
  // @@protoc_insertion_point(field_set:systemConfiguration.maxMismatchProb)
}
inline float systemConfiguration::_internal_maxmismatchprob() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.maxmismatchprob_;
}
inline void systemConfiguration::_internal_set_maxmismatchprob(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.maxmismatchprob_ = value;
}

// float centroidCompareThreshold = 12;
inline void systemConfiguration::clear_centroidcomparethreshold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.centroidcomparethreshold_ = 0;
}
inline float systemConfiguration::centroidcomparethreshold() const {
  // @@protoc_insertion_point(field_get:systemConfiguration.centroidCompareThreshold)
  return _internal_centroidcomparethreshold();
}
inline void systemConfiguration::set_centroidcomparethreshold(float value) {
  _internal_set_centroidcomparethreshold(value);
  // @@protoc_insertion_point(field_set:systemConfiguration.centroidCompareThreshold)
}
inline float systemConfiguration::_internal_centroidcomparethreshold() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.centroidcomparethreshold_;
}
inline void systemConfiguration::_internal_set_centroidcomparethreshold(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.centroidcomparethreshold_ = value;
}

// float attitudeCompareThreshold = 13;
inline void systemConfiguration::clear_attitudecomparethreshold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attitudecomparethreshold_ = 0;
}
inline float systemConfiguration::attitudecomparethreshold() const {
  // @@protoc_insertion_point(field_get:systemConfiguration.attitudeCompareThreshold)
  return _internal_attitudecomparethreshold();
}
inline void systemConfiguration::set_attitudecomparethreshold(float value) {
  _internal_set_attitudecomparethreshold(value);
  // @@protoc_insertion_point(field_set:systemConfiguration.attitudeCompareThreshold)
}
inline float systemConfiguration::_internal_attitudecomparethreshold() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.attitudecomparethreshold_;
}
inline void systemConfiguration::_internal_set_attitudecomparethreshold(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attitudecomparethreshold_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_config_2eproto_2epb_2eh
