// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: config.proto
// Protobuf C++ Version: 5.27.3

#include "config.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr cameraConfiguration::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : deviceid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        focallength_{0},
        pixelsize_{0},
        fov_{0},
        xresolution_{0},
        yresolution_{0},
        pixelrate_{0},
        index_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR cameraConfiguration::cameraConfiguration(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct cameraConfigurationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR cameraConfigurationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~cameraConfigurationDefaultTypeInternal() {}
  union {
    cameraConfiguration _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 cameraConfigurationDefaultTypeInternal _cameraConfiguration_default_instance_;

inline constexpr systemConfiguration::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : cameras_{},
        centroidalgo_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        attitudealgo_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        databasepath_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        idalgo_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        centroidmagfilter_{0},
        angulartolerance_{0},
        centroidfilterbrightest_{0},
        estimatednumfalsestars_{0},
        maxmismatchprob_{0},
        centroidcomparethreshold_{0},
        attitudecomparethreshold_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR systemConfiguration::systemConfiguration(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct systemConfigurationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR systemConfigurationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~systemConfigurationDefaultTypeInternal() {}
  union {
    systemConfiguration _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 systemConfigurationDefaultTypeInternal _systemConfiguration_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_config_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_config_2eproto = nullptr;
const ::uint32_t
    TableStruct_config_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::cameraConfiguration, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cameraConfiguration, _impl_.index_),
        PROTOBUF_FIELD_OFFSET(::cameraConfiguration, _impl_.deviceid_),
        PROTOBUF_FIELD_OFFSET(::cameraConfiguration, _impl_.focallength_),
        PROTOBUF_FIELD_OFFSET(::cameraConfiguration, _impl_.pixelsize_),
        PROTOBUF_FIELD_OFFSET(::cameraConfiguration, _impl_.fov_),
        PROTOBUF_FIELD_OFFSET(::cameraConfiguration, _impl_.xresolution_),
        PROTOBUF_FIELD_OFFSET(::cameraConfiguration, _impl_.yresolution_),
        PROTOBUF_FIELD_OFFSET(::cameraConfiguration, _impl_.pixelrate_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.cameras_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.centroidalgo_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.attitudealgo_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.centroidmagfilter_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.databasepath_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.idalgo_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.angulartolerance_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.centroidfilterbrightest_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.estimatednumfalsestars_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.maxmismatchprob_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.centroidcomparethreshold_),
        PROTOBUF_FIELD_OFFSET(::systemConfiguration, _impl_.attitudecomparethreshold_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::cameraConfiguration)},
        {16, -1, -1, sizeof(::systemConfiguration)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_cameraConfiguration_default_instance_._instance,
    &::_systemConfiguration_default_instance_._instance,
};
const char descriptor_table_protodef_config_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014config.proto\"\250\001\n\023cameraConfiguration\022\r"
    "\n\005index\030\010 \001(\005\022\020\n\010deviceID\030\001 \001(\t\022\023\n\013focal"
    "Length\030\002 \001(\001\022\021\n\tpixelSize\030\003 \001(\001\022\013\n\003fov\030\004"
    " \001(\001\022\023\n\013xResolution\030\005 \001(\005\022\023\n\013yResolution"
    "\030\006 \001(\005\022\021\n\tpixelRate\030\007 \001(\001\"\341\002\n\023systemConf"
    "iguration\022%\n\007cameras\030\001 \003(\0132\024.cameraConfi"
    "guration\022\024\n\014centroidAlgo\030\002 \001(\t\022\024\n\014attitu"
    "deAlgo\030\003 \001(\t\022\031\n\021centroidMagFilter\030\004 \001(\001\022"
    "\024\n\014databasePath\030\005 \001(\t\022\016\n\006idAlgo\030\006 \001(\t\022\030\n"
    "\020angularTolerance\030\010 \001(\001\022\037\n\027centroidFilte"
    "rBrightest\030\t \001(\005\022\036\n\026estimatedNumFalseSta"
    "rs\030\n \001(\005\022\027\n\017maxMismatchProb\030\013 \001(\002\022 \n\030cen"
    "troidCompareThreshold\030\014 \001(\002\022 \n\030attitudeC"
    "ompareThreshold\030\r \001(\002b\006proto3"
};
static ::absl::once_flag descriptor_table_config_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_config_2eproto = {
    false,
    false,
    549,
    descriptor_table_protodef_config_2eproto,
    "config.proto",
    &descriptor_table_config_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_config_2eproto::offsets,
    file_level_enum_descriptors_config_2eproto,
    file_level_service_descriptors_config_2eproto,
};
// ===================================================================

class cameraConfiguration::_Internal {
 public:
};

cameraConfiguration::cameraConfiguration(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cameraConfiguration)
}
inline PROTOBUF_NDEBUG_INLINE cameraConfiguration::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cameraConfiguration& from_msg)
      : deviceid_(arena, from.deviceid_),
        _cached_size_{0} {}

cameraConfiguration::cameraConfiguration(
    ::google::protobuf::Arena* arena,
    const cameraConfiguration& from)
    : ::google::protobuf::Message(arena) {
  cameraConfiguration* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, focallength_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, focallength_),
           offsetof(Impl_, index_) -
               offsetof(Impl_, focallength_) +
               sizeof(Impl_::index_));

  // @@protoc_insertion_point(copy_constructor:cameraConfiguration)
}
inline PROTOBUF_NDEBUG_INLINE cameraConfiguration::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : deviceid_(arena),
        _cached_size_{0} {}

inline void cameraConfiguration::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, focallength_),
           0,
           offsetof(Impl_, index_) -
               offsetof(Impl_, focallength_) +
               sizeof(Impl_::index_));
}
cameraConfiguration::~cameraConfiguration() {
  // @@protoc_insertion_point(destructor:cameraConfiguration)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void cameraConfiguration::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.deviceid_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
cameraConfiguration::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_._cached_size_),
              false,
          },
          &cameraConfiguration::MergeImpl,
          &cameraConfiguration::kDescriptorMethods,
          &descriptor_table_config_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 44, 2> cameraConfiguration::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_cameraConfiguration_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cameraConfiguration>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 index = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(cameraConfiguration, _impl_.index_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.index_)}},
    // string deviceID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.deviceid_)}},
    // double focalLength = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.focallength_)}},
    // double pixelSize = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.pixelsize_)}},
    // double fov = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.fov_)}},
    // int32 xResolution = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(cameraConfiguration, _impl_.xresolution_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.xresolution_)}},
    // int32 yResolution = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(cameraConfiguration, _impl_.yresolution_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.yresolution_)}},
    // double pixelRate = 7;
    {::_pbi::TcParser::FastF64S1,
     {57, 63, 0, PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.pixelrate_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string deviceID = 1;
    {PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.deviceid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double focalLength = 2;
    {PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.focallength_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double pixelSize = 3;
    {PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.pixelsize_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double fov = 4;
    {PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.fov_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // int32 xResolution = 5;
    {PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.xresolution_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 yResolution = 6;
    {PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.yresolution_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // double pixelRate = 7;
    {PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.pixelrate_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // int32 index = 8;
    {PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.index_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\23\10\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    "cameraConfiguration"
    "deviceID"
  }},
};

PROTOBUF_NOINLINE void cameraConfiguration::Clear() {
// @@protoc_insertion_point(message_clear_start:cameraConfiguration)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.deviceid_.ClearToEmpty();
  ::memset(&_impl_.focallength_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.index_) -
      reinterpret_cast<char*>(&_impl_.focallength_)) + sizeof(_impl_.index_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* cameraConfiguration::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cameraConfiguration)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string deviceID = 1;
  if (!this->_internal_deviceid().empty()) {
    const std::string& _s = this->_internal_deviceid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cameraConfiguration.deviceID");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // double focalLength = 2;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_focallength = this->_internal_focallength();
  ::uint64_t raw_focallength;
  memcpy(&raw_focallength, &tmp_focallength, sizeof(tmp_focallength));
  if (raw_focallength != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this->_internal_focallength(), target);
  }

  // double pixelSize = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_pixelsize = this->_internal_pixelsize();
  ::uint64_t raw_pixelsize;
  memcpy(&raw_pixelsize, &tmp_pixelsize, sizeof(tmp_pixelsize));
  if (raw_pixelsize != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this->_internal_pixelsize(), target);
  }

  // double fov = 4;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_fov = this->_internal_fov();
  ::uint64_t raw_fov;
  memcpy(&raw_fov, &tmp_fov, sizeof(tmp_fov));
  if (raw_fov != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        4, this->_internal_fov(), target);
  }

  // int32 xResolution = 5;
  if (this->_internal_xresolution() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_xresolution(), target);
  }

  // int32 yResolution = 6;
  if (this->_internal_yresolution() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<6>(
            stream, this->_internal_yresolution(), target);
  }

  // double pixelRate = 7;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_pixelrate = this->_internal_pixelrate();
  ::uint64_t raw_pixelrate;
  memcpy(&raw_pixelrate, &tmp_pixelrate, sizeof(tmp_pixelrate));
  if (raw_pixelrate != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        7, this->_internal_pixelrate(), target);
  }

  // int32 index = 8;
  if (this->_internal_index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<8>(
            stream, this->_internal_index(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cameraConfiguration)
  return target;
}

::size_t cameraConfiguration::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cameraConfiguration)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string deviceID = 1;
  if (!this->_internal_deviceid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_deviceid());
  }

  // double focalLength = 2;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_focallength = this->_internal_focallength();
  ::uint64_t raw_focallength;
  memcpy(&raw_focallength, &tmp_focallength, sizeof(tmp_focallength));
  if (raw_focallength != 0) {
    total_size += 9;
  }

  // double pixelSize = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_pixelsize = this->_internal_pixelsize();
  ::uint64_t raw_pixelsize;
  memcpy(&raw_pixelsize, &tmp_pixelsize, sizeof(tmp_pixelsize));
  if (raw_pixelsize != 0) {
    total_size += 9;
  }

  // double fov = 4;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_fov = this->_internal_fov();
  ::uint64_t raw_fov;
  memcpy(&raw_fov, &tmp_fov, sizeof(tmp_fov));
  if (raw_fov != 0) {
    total_size += 9;
  }

  // int32 xResolution = 5;
  if (this->_internal_xresolution() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_xresolution());
  }

  // int32 yResolution = 6;
  if (this->_internal_yresolution() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_yresolution());
  }

  // double pixelRate = 7;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_pixelrate = this->_internal_pixelrate();
  ::uint64_t raw_pixelrate;
  memcpy(&raw_pixelrate, &tmp_pixelrate, sizeof(tmp_pixelrate));
  if (raw_pixelrate != 0) {
    total_size += 9;
  }

  // int32 index = 8;
  if (this->_internal_index() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_index());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void cameraConfiguration::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<cameraConfiguration*>(&to_msg);
  auto& from = static_cast<const cameraConfiguration&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cameraConfiguration)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_deviceid().empty()) {
    _this->_internal_set_deviceid(from._internal_deviceid());
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_focallength = from._internal_focallength();
  ::uint64_t raw_focallength;
  memcpy(&raw_focallength, &tmp_focallength, sizeof(tmp_focallength));
  if (raw_focallength != 0) {
    _this->_impl_.focallength_ = from._impl_.focallength_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_pixelsize = from._internal_pixelsize();
  ::uint64_t raw_pixelsize;
  memcpy(&raw_pixelsize, &tmp_pixelsize, sizeof(tmp_pixelsize));
  if (raw_pixelsize != 0) {
    _this->_impl_.pixelsize_ = from._impl_.pixelsize_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_fov = from._internal_fov();
  ::uint64_t raw_fov;
  memcpy(&raw_fov, &tmp_fov, sizeof(tmp_fov));
  if (raw_fov != 0) {
    _this->_impl_.fov_ = from._impl_.fov_;
  }
  if (from._internal_xresolution() != 0) {
    _this->_impl_.xresolution_ = from._impl_.xresolution_;
  }
  if (from._internal_yresolution() != 0) {
    _this->_impl_.yresolution_ = from._impl_.yresolution_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_pixelrate = from._internal_pixelrate();
  ::uint64_t raw_pixelrate;
  memcpy(&raw_pixelrate, &tmp_pixelrate, sizeof(tmp_pixelrate));
  if (raw_pixelrate != 0) {
    _this->_impl_.pixelrate_ = from._impl_.pixelrate_;
  }
  if (from._internal_index() != 0) {
    _this->_impl_.index_ = from._impl_.index_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void cameraConfiguration::CopyFrom(const cameraConfiguration& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cameraConfiguration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void cameraConfiguration::InternalSwap(cameraConfiguration* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.deviceid_, &other->_impl_.deviceid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.index_)
      + sizeof(cameraConfiguration::_impl_.index_)
      - PROTOBUF_FIELD_OFFSET(cameraConfiguration, _impl_.focallength_)>(
          reinterpret_cast<char*>(&_impl_.focallength_),
          reinterpret_cast<char*>(&other->_impl_.focallength_));
}

::google::protobuf::Metadata cameraConfiguration::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class systemConfiguration::_Internal {
 public:
};

systemConfiguration::systemConfiguration(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:systemConfiguration)
}
inline PROTOBUF_NDEBUG_INLINE systemConfiguration::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::systemConfiguration& from_msg)
      : cameras_{visibility, arena, from.cameras_},
        centroidalgo_(arena, from.centroidalgo_),
        attitudealgo_(arena, from.attitudealgo_),
        databasepath_(arena, from.databasepath_),
        idalgo_(arena, from.idalgo_),
        _cached_size_{0} {}

systemConfiguration::systemConfiguration(
    ::google::protobuf::Arena* arena,
    const systemConfiguration& from)
    : ::google::protobuf::Message(arena) {
  systemConfiguration* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, centroidmagfilter_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, centroidmagfilter_),
           offsetof(Impl_, attitudecomparethreshold_) -
               offsetof(Impl_, centroidmagfilter_) +
               sizeof(Impl_::attitudecomparethreshold_));

  // @@protoc_insertion_point(copy_constructor:systemConfiguration)
}
inline PROTOBUF_NDEBUG_INLINE systemConfiguration::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : cameras_{visibility, arena},
        centroidalgo_(arena),
        attitudealgo_(arena),
        databasepath_(arena),
        idalgo_(arena),
        _cached_size_{0} {}

inline void systemConfiguration::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, centroidmagfilter_),
           0,
           offsetof(Impl_, attitudecomparethreshold_) -
               offsetof(Impl_, centroidmagfilter_) +
               sizeof(Impl_::attitudecomparethreshold_));
}
systemConfiguration::~systemConfiguration() {
  // @@protoc_insertion_point(destructor:systemConfiguration)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void systemConfiguration::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.centroidalgo_.Destroy();
  _impl_.attitudealgo_.Destroy();
  _impl_.databasepath_.Destroy();
  _impl_.idalgo_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
systemConfiguration::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_._cached_size_),
              false,
          },
          &systemConfiguration::MergeImpl,
          &systemConfiguration::kDescriptorMethods,
          &descriptor_table_config_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 12, 1, 78, 2> systemConfiguration::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    13, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294959168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    12,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_systemConfiguration_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::systemConfiguration>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .cameraConfiguration cameras = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.cameras_)}},
    // string centroidAlgo = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.centroidalgo_)}},
    // string attitudeAlgo = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.attitudealgo_)}},
    // double centroidMagFilter = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.centroidmagfilter_)}},
    // string databasePath = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.databasepath_)}},
    // string idAlgo = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.idalgo_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // double angularTolerance = 8;
    {::_pbi::TcParser::FastF64S1,
     {65, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.angulartolerance_)}},
    // int32 centroidFilterBrightest = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(systemConfiguration, _impl_.centroidfilterbrightest_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.centroidfilterbrightest_)}},
    // int32 estimatedNumFalseStars = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(systemConfiguration, _impl_.estimatednumfalsestars_), 63>(),
     {80, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.estimatednumfalsestars_)}},
    // float maxMismatchProb = 11;
    {::_pbi::TcParser::FastF32S1,
     {93, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.maxmismatchprob_)}},
    // float centroidCompareThreshold = 12;
    {::_pbi::TcParser::FastF32S1,
     {101, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.centroidcomparethreshold_)}},
    // float attitudeCompareThreshold = 13;
    {::_pbi::TcParser::FastF32S1,
     {109, 63, 0, PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.attitudecomparethreshold_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .cameraConfiguration cameras = 1;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.cameras_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // string centroidAlgo = 2;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.centroidalgo_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string attitudeAlgo = 3;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.attitudealgo_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double centroidMagFilter = 4;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.centroidmagfilter_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // string databasePath = 5;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.databasepath_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string idAlgo = 6;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.idalgo_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double angularTolerance = 8;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.angulartolerance_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // int32 centroidFilterBrightest = 9;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.centroidfilterbrightest_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 estimatedNumFalseStars = 10;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.estimatednumfalsestars_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // float maxMismatchProb = 11;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.maxmismatchprob_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float centroidCompareThreshold = 12;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.centroidcomparethreshold_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float attitudeCompareThreshold = 13;
    {PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.attitudecomparethreshold_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }}, {{
    {::_pbi::TcParser::GetTable<::cameraConfiguration>()},
  }}, {{
    "\23\0\14\14\0\14\6\0\0\0\0\0\0\0\0\0"
    "systemConfiguration"
    "centroidAlgo"
    "attitudeAlgo"
    "databasePath"
    "idAlgo"
  }},
};

PROTOBUF_NOINLINE void systemConfiguration::Clear() {
// @@protoc_insertion_point(message_clear_start:systemConfiguration)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.cameras_.Clear();
  _impl_.centroidalgo_.ClearToEmpty();
  _impl_.attitudealgo_.ClearToEmpty();
  _impl_.databasepath_.ClearToEmpty();
  _impl_.idalgo_.ClearToEmpty();
  ::memset(&_impl_.centroidmagfilter_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.attitudecomparethreshold_) -
      reinterpret_cast<char*>(&_impl_.centroidmagfilter_)) + sizeof(_impl_.attitudecomparethreshold_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* systemConfiguration::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:systemConfiguration)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .cameraConfiguration cameras = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_cameras_size());
       i < n; i++) {
    const auto& repfield = this->_internal_cameras().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // string centroidAlgo = 2;
  if (!this->_internal_centroidalgo().empty()) {
    const std::string& _s = this->_internal_centroidalgo();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "systemConfiguration.centroidAlgo");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string attitudeAlgo = 3;
  if (!this->_internal_attitudealgo().empty()) {
    const std::string& _s = this->_internal_attitudealgo();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "systemConfiguration.attitudeAlgo");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // double centroidMagFilter = 4;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_centroidmagfilter = this->_internal_centroidmagfilter();
  ::uint64_t raw_centroidmagfilter;
  memcpy(&raw_centroidmagfilter, &tmp_centroidmagfilter, sizeof(tmp_centroidmagfilter));
  if (raw_centroidmagfilter != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        4, this->_internal_centroidmagfilter(), target);
  }

  // string databasePath = 5;
  if (!this->_internal_databasepath().empty()) {
    const std::string& _s = this->_internal_databasepath();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "systemConfiguration.databasePath");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // string idAlgo = 6;
  if (!this->_internal_idalgo().empty()) {
    const std::string& _s = this->_internal_idalgo();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "systemConfiguration.idAlgo");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // double angularTolerance = 8;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_angulartolerance = this->_internal_angulartolerance();
  ::uint64_t raw_angulartolerance;
  memcpy(&raw_angulartolerance, &tmp_angulartolerance, sizeof(tmp_angulartolerance));
  if (raw_angulartolerance != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        8, this->_internal_angulartolerance(), target);
  }

  // int32 centroidFilterBrightest = 9;
  if (this->_internal_centroidfilterbrightest() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<9>(
            stream, this->_internal_centroidfilterbrightest(), target);
  }

  // int32 estimatedNumFalseStars = 10;
  if (this->_internal_estimatednumfalsestars() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<10>(
            stream, this->_internal_estimatednumfalsestars(), target);
  }

  // float maxMismatchProb = 11;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_maxmismatchprob = this->_internal_maxmismatchprob();
  ::uint32_t raw_maxmismatchprob;
  memcpy(&raw_maxmismatchprob, &tmp_maxmismatchprob, sizeof(tmp_maxmismatchprob));
  if (raw_maxmismatchprob != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        11, this->_internal_maxmismatchprob(), target);
  }

  // float centroidCompareThreshold = 12;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_centroidcomparethreshold = this->_internal_centroidcomparethreshold();
  ::uint32_t raw_centroidcomparethreshold;
  memcpy(&raw_centroidcomparethreshold, &tmp_centroidcomparethreshold, sizeof(tmp_centroidcomparethreshold));
  if (raw_centroidcomparethreshold != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        12, this->_internal_centroidcomparethreshold(), target);
  }

  // float attitudeCompareThreshold = 13;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_attitudecomparethreshold = this->_internal_attitudecomparethreshold();
  ::uint32_t raw_attitudecomparethreshold;
  memcpy(&raw_attitudecomparethreshold, &tmp_attitudecomparethreshold, sizeof(tmp_attitudecomparethreshold));
  if (raw_attitudecomparethreshold != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        13, this->_internal_attitudecomparethreshold(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:systemConfiguration)
  return target;
}

::size_t systemConfiguration::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:systemConfiguration)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .cameraConfiguration cameras = 1;
  total_size += 1UL * this->_internal_cameras_size();
  for (const auto& msg : this->_internal_cameras()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string centroidAlgo = 2;
  if (!this->_internal_centroidalgo().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_centroidalgo());
  }

  // string attitudeAlgo = 3;
  if (!this->_internal_attitudealgo().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_attitudealgo());
  }

  // string databasePath = 5;
  if (!this->_internal_databasepath().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_databasepath());
  }

  // string idAlgo = 6;
  if (!this->_internal_idalgo().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_idalgo());
  }

  // double centroidMagFilter = 4;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_centroidmagfilter = this->_internal_centroidmagfilter();
  ::uint64_t raw_centroidmagfilter;
  memcpy(&raw_centroidmagfilter, &tmp_centroidmagfilter, sizeof(tmp_centroidmagfilter));
  if (raw_centroidmagfilter != 0) {
    total_size += 9;
  }

  // double angularTolerance = 8;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_angulartolerance = this->_internal_angulartolerance();
  ::uint64_t raw_angulartolerance;
  memcpy(&raw_angulartolerance, &tmp_angulartolerance, sizeof(tmp_angulartolerance));
  if (raw_angulartolerance != 0) {
    total_size += 9;
  }

  // int32 centroidFilterBrightest = 9;
  if (this->_internal_centroidfilterbrightest() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_centroidfilterbrightest());
  }

  // int32 estimatedNumFalseStars = 10;
  if (this->_internal_estimatednumfalsestars() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_estimatednumfalsestars());
  }

  // float maxMismatchProb = 11;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_maxmismatchprob = this->_internal_maxmismatchprob();
  ::uint32_t raw_maxmismatchprob;
  memcpy(&raw_maxmismatchprob, &tmp_maxmismatchprob, sizeof(tmp_maxmismatchprob));
  if (raw_maxmismatchprob != 0) {
    total_size += 5;
  }

  // float centroidCompareThreshold = 12;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_centroidcomparethreshold = this->_internal_centroidcomparethreshold();
  ::uint32_t raw_centroidcomparethreshold;
  memcpy(&raw_centroidcomparethreshold, &tmp_centroidcomparethreshold, sizeof(tmp_centroidcomparethreshold));
  if (raw_centroidcomparethreshold != 0) {
    total_size += 5;
  }

  // float attitudeCompareThreshold = 13;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_attitudecomparethreshold = this->_internal_attitudecomparethreshold();
  ::uint32_t raw_attitudecomparethreshold;
  memcpy(&raw_attitudecomparethreshold, &tmp_attitudecomparethreshold, sizeof(tmp_attitudecomparethreshold));
  if (raw_attitudecomparethreshold != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void systemConfiguration::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<systemConfiguration*>(&to_msg);
  auto& from = static_cast<const systemConfiguration&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:systemConfiguration)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_cameras()->MergeFrom(
      from._internal_cameras());
  if (!from._internal_centroidalgo().empty()) {
    _this->_internal_set_centroidalgo(from._internal_centroidalgo());
  }
  if (!from._internal_attitudealgo().empty()) {
    _this->_internal_set_attitudealgo(from._internal_attitudealgo());
  }
  if (!from._internal_databasepath().empty()) {
    _this->_internal_set_databasepath(from._internal_databasepath());
  }
  if (!from._internal_idalgo().empty()) {
    _this->_internal_set_idalgo(from._internal_idalgo());
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_centroidmagfilter = from._internal_centroidmagfilter();
  ::uint64_t raw_centroidmagfilter;
  memcpy(&raw_centroidmagfilter, &tmp_centroidmagfilter, sizeof(tmp_centroidmagfilter));
  if (raw_centroidmagfilter != 0) {
    _this->_impl_.centroidmagfilter_ = from._impl_.centroidmagfilter_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_angulartolerance = from._internal_angulartolerance();
  ::uint64_t raw_angulartolerance;
  memcpy(&raw_angulartolerance, &tmp_angulartolerance, sizeof(tmp_angulartolerance));
  if (raw_angulartolerance != 0) {
    _this->_impl_.angulartolerance_ = from._impl_.angulartolerance_;
  }
  if (from._internal_centroidfilterbrightest() != 0) {
    _this->_impl_.centroidfilterbrightest_ = from._impl_.centroidfilterbrightest_;
  }
  if (from._internal_estimatednumfalsestars() != 0) {
    _this->_impl_.estimatednumfalsestars_ = from._impl_.estimatednumfalsestars_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_maxmismatchprob = from._internal_maxmismatchprob();
  ::uint32_t raw_maxmismatchprob;
  memcpy(&raw_maxmismatchprob, &tmp_maxmismatchprob, sizeof(tmp_maxmismatchprob));
  if (raw_maxmismatchprob != 0) {
    _this->_impl_.maxmismatchprob_ = from._impl_.maxmismatchprob_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_centroidcomparethreshold = from._internal_centroidcomparethreshold();
  ::uint32_t raw_centroidcomparethreshold;
  memcpy(&raw_centroidcomparethreshold, &tmp_centroidcomparethreshold, sizeof(tmp_centroidcomparethreshold));
  if (raw_centroidcomparethreshold != 0) {
    _this->_impl_.centroidcomparethreshold_ = from._impl_.centroidcomparethreshold_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_attitudecomparethreshold = from._internal_attitudecomparethreshold();
  ::uint32_t raw_attitudecomparethreshold;
  memcpy(&raw_attitudecomparethreshold, &tmp_attitudecomparethreshold, sizeof(tmp_attitudecomparethreshold));
  if (raw_attitudecomparethreshold != 0) {
    _this->_impl_.attitudecomparethreshold_ = from._impl_.attitudecomparethreshold_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void systemConfiguration::CopyFrom(const systemConfiguration& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:systemConfiguration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void systemConfiguration::InternalSwap(systemConfiguration* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.cameras_.InternalSwap(&other->_impl_.cameras_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.centroidalgo_, &other->_impl_.centroidalgo_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.attitudealgo_, &other->_impl_.attitudealgo_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.databasepath_, &other->_impl_.databasepath_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.idalgo_, &other->_impl_.idalgo_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.attitudecomparethreshold_)
      + sizeof(systemConfiguration::_impl_.attitudecomparethreshold_)
      - PROTOBUF_FIELD_OFFSET(systemConfiguration, _impl_.centroidmagfilter_)>(
          reinterpret_cast<char*>(&_impl_.centroidmagfilter_),
          reinterpret_cast<char*>(&other->_impl_.centroidmagfilter_));
}

::google::protobuf::Metadata systemConfiguration::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_config_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
